export const ordersList = [
  {
    number: "034535",
    name: "Death Star Starship Main бургер",
    status: "Создан",
    date: "2021-07-15 17:50",
    price: 480,
    ingredients: [
      {
        name: "Флюоресцентная булка R2-D3",
        count: 2,
        price: 20,
        image: "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
      },
      {
        name: "Филе Люминесцентного тетраодонтимформа",
        count: 1,
        price: 300,
        image: "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      },
      {
        name: "Соус традиционный галактический",
        count: 1,
        price: 30,
        image: "https://code.s3.yandex.net/react/code/sauce-03-mobile.png",
      },
      {
        name: "Плоды фалленианского дерева",
        count: 1,
        price: 80,
        image: "https://code.s3.yandex.net/react/code/sp_1-mobile.png",
      },
    ],
  },
  {
    number: "034533",
    name: "Black Hole Singularity острый бургер",
    status: "Выполнен",
    date: "2021-07-14 13:50",
    price: 510,
    ingredients: [
      {
        name: "Флюоресцентная булка R2-D3",
        count: 2,
        price: 20,
        image: "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
      },
      {
        name: "Филе Люминесцентного тетраодонтимформа",
        count: 1,
        price: 300,
        image: "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      },
      {
        name: "Соус традиционный галактический",
        count: 1,
        price: 30,
        image: "https://code.s3.yandex.net/react/code/sauce-03-mobile.png",
      },
      {
        name: "Плоды фалленианского дерева",
        count: 1,
        price: 80,
        image: "https://code.s3.yandex.net/react/code/sp_1-mobile.png",
      },
      {
        name: "Мясо бессмертных моллюсков Protostomia",
        image: "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
        price: 1337,
        count: 1,
      },
      {
        name: "Мини-салат Экзо-Плантаго",
        image: "https://code.s3.yandex.net/react/code/salad-mobile.png",
        price: 4400,
        count: 2,
      },
      {
        name: "Хрустящие минеральные кольца",
        image: "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
        price: 300,
        count: 3,
      },
    ],
  },
  {
    number: "034534",
    name: "Interstellar бургер",
    status: "Готовится",
    date: "2021-07-13 13:20",
    price: 560,
    ingredients: [
      {
        name: "Флюоресцентная булка R2-D3",
        count: 2,
        price: 20,
        image: "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
      },
      {
        name: "Филе Люминесцентного тетраодонтимформа",
        count: 1,
        price: 300,
        image: "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      },
      {
        name: "Соус традиционный галактический",
        count: 1,
        price: 30,
        image: "https://code.s3.yandex.net/react/code/sauce-03-mobile.png",
      },
      {
        name: "Плоды фалленианского дерева",
        count: 1,
        price: 80,
        image: "https://code.s3.yandex.net/react/code/sp_1-mobile.png",
      },
      {
        name: "Хрустящие минеральные кольца",
        image: "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
        price: 300,
        count: 3,
      },
    ],
  },
  {
    number: "034539",
    name: "Supernova Infinity бургер",
    status: "Выполнен",
    date: "2021-07-12 16:50",
    price: 480,
    ingredients: [
      {
        name: "Флюоресцентная булка R2-D3",
        count: 2,
        price: 20,
        image: "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
      },
      {
        name: "Плоды фалленианского дерева",
        count: 1,
        price: 80,
        image: "https://code.s3.yandex.net/react/code/sp_1-mobile.png",
      },
    ],
  },
];
