export const ADD_CONSTRUCTOR_INGREDIENT = "ADD_CONSTRUCTOR_INGREDIENT";
export const REMOVE_CONSTRUCTOR_INGREDIENT = "REMOVE_CONSTRUCTOR_INGREDIENT";
export const REORDER_CONSTRUCTOR_INGREDIENTS =
  "REORDER_CONSTRUCTOR_INGREDIENTS";
